services:
  webserver:
    build:
      context: ./.docker/server_http
      args:
        TIMEZONE: ${TIMEZONE}
    labels:
      ho.ctf.cyrhades: "1"
    ports:
      - ${PORT}:80
  cloud:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: "baddevbutbetter"
      FTP_USER_PASS: "8shm2gFXvL22UmKln"
      FTP_USER_HOME: "/home/documents"
    restart: always
